### ISSUE TITLE
Doesn't work in all regions

### ISSUE THREAD

**Issue by fabdrol** [dyashkir/amazon-s3-url-signer#14]
My endpoint is not supported. Error message: 

`The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.`

I'm on `eu-west-1`.

**Comment by jonathanasquier** [comment]
```
var bucket = sig.urlSigner(accessKeyId, secretAccessKey, {
    host : 's3-eu-west-1.amazonaws.com'
});
```
Had to read the code.

Dyashkir could you update the README merge the pull requests and publish please? :) Would be awesome!

**Comment by dyashkir** [comment]
Added to README, thank you
